### ISSUE TITLE
SSL initContainer failed with "keytool error: java.io.IOException: keystore password was incorrect"

### ISSUE THREAD

**Issue by AkarshES** [lucidworks/solr-helm-chart#6]
I followed the instructions given for enabling SSL. The init container setup-keystore-and-properties errors out with the following output. I have used the default password of 'changeit' for the password.

unable to write 'random state'
Importing keystore /tmp/keystore.pkcs12 to /tmp/keystore/solr.jks...
keytool error: java.io.IOException: keystore password was incorrect

**Comment by snooyen** [comment]
@AkarshES Were you able to resolve this?

**Comment by AkarshES** [comment]
Nope, I could not figure it. Its close to a year now, I am not sure what I ended up trying to debug.

**Comment by snooyen** [comment]
Really strange.  I can't get it to work on EKS, but I'm seeing it work on AKS.

**Comment by snooyen** [comment]
Figured it out.  
You need to set a Subject on the certificate that you create

**Comment by snooyen** [comment]
Here's the verbose error:
```
keytool error: java.io.IOException: keystore password was incorrect
java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(Unknown Source)
	at java.base/sun.security.tools.keytool.Main.doCommands(Unknown Source)
	at java.base/sun.security.tools.keytool.Main.run(Unknown Source)
	at java.base/sun.security.tools.keytool.Main.main(Unknown Source)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: java.security.cert.CertificateParsingException: X.509 Certificate is incomplete: subject field is empty, and SubjectAlternativeName extension is absent
```

**Comment by DumboJet** [comment]
Same issue here.
And I do have a `CN` on my certificate, matching the one on my `SOLR_HOST` environment variable.
